# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache:
- bundler
script: bundle exec rake

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - ruby-head

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_6_0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
